# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a5626d16646408856239670ef67d4d581e67556afc1c3d9704cc89e6cb315018b08e42ec1f28d853acb0455ccef6aff82716b87cd758df2e84d6022abc54f0

test:
  secret_key_base: cd7977bd70e4b815bbceac3e9a6b447c0fa4cdbfadfb6583d0f870f2cdf1ce4cf8448c500734dc26036b0cec8142204352a2f322cab7557c2cadea365c936a69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
